version: "3.7"

services:
  cosuno-backend:
    env_file:
      - .env
    image: node:16-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - $PORT:$PORT
    working_dir: /backend
    volumes:
      - ./:/backend
